# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: myapp
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_USER/$DOCKER_IMAGE
          tag: $DOCKER_TAG

      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_USER/$DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

version: 2.1

orbs:
  docker: circleci/docker@1.6.0

workflows:
  commit:
    jobs:
      - build-and-push

